name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Tailscale and connect
      run: |
        curl -fsSL https://pkgs.tailscale.com/stable/tailscale_1.66.4_amd64.tgz | tar xz
        sudo install tailscale_1.66.4_amd64/tailscale /usr/bin/tailscale
        sudo install tailscale_1.66.4_amd64/tailscaled /usr/sbin/tailscaled
        sudo mkdir -p /var/lib/tailscale
        sudo tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
        sleep 10
        tailscale version
        tailscale status || true
        sudo tailscale up --auth-key "${{ secrets.TAILSCALE_AUTH_KEY }}" --hostname=github-runner --ssh

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.TAILSCALE_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy App via SSH
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.TAILSCALE_SSH_USER }}@${{ secrets.TAILSCALE_SSH_HOST }} << 'EOF'
          echo "🔄 Pulling latest code..."
          cd ~/test
          git pull

          echo "📴 Sending SIGTERM to app.py..."
          pkill -SIGTERM -f app.py || echo "No app.py process found."

          echo "🚀 Restarting app.py..."
          nohup python3 app.py > app.log 2>&1 &

          echo "✅ Deployment finished."
        EOF
