name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.TAILSCALE_SSH_HOST }} >> ~/.ssh/known_hosts || true

        TAILSCALE_IP=$(tailscale ip -4 ${{ secrets.TAILSCALE_SSH_HOST }})
        echo "Tailscale IP: $TAILSCALE_IP"
        echo "$TAILSCALE_IP" > tailscale_ip.txt
        ssh-keyscan -H "$TAILSCALE_IP" >> ~/.ssh/known_hosts || true

    - name: Deploy App via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.TAILSCALE_SSH_USER }}@${{ secrets.TAILSCALE_SSH_HOST }} << 'EOF'
          echo "🔄 Pulling latest code..."
          cd ~/test
          git pull

          echo "📴 Sending SIGTERM to app.py..."
          pkill -SIGTERM -f app.py || echo "No app.py process found."

          echo "🚀 Restarting app.py..."
          nohup python3 app.py > app.log 2>&1 &

          echo "✅ Deployment finished."
        EOF
    - name: Restart Flask app with PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.TAILSCALE_SSH_HOST }}
        username: ${{ secrets.TAILSCALE_SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
         cd /home/${{ secrets.TAILSCALE_SSH_USER }}/app
         pip install -r requirements.txt
         pm2 restart flask-app

