name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.TAILSCALE_SSH_HOST }} >> ~/.ssh/known_hosts || true

    - name: Deploy App via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.TAILSCALE_SSH_USER }}@${{ secrets.TAILSCALE_SSH_HOST }} << 'EOF'
          echo "🔄 Pulling latest code..."
          cd ~/test
          git pull

          echo "📴 Sending SIGTERM to app.py..."
          pkill -SIGTERM -f app.py || echo "No app.py process found."

          echo "🚀 Restarting app.py..."
          nohup python3 app.py > app.log 2>&1 &

          echo "✅ Deployment finished."
        EOF
